# **Numpy**
Numerical Python

It is a Python package creating and processing numeric arrays.

**Why Numpy?**

1. NumPy vs Lists (speed, functionality)

- Contimuous memory

- Less memory

- Built in functionalities

2. Applications of NumPy
- Mathematics
- Vector Processing
- Image procession
- Backend
- Machine Leanign

....



install and import

How to create and initialize?

Working with Images

Accessing, indexing, Slicing, Masking

**Install and Import**

In [0]:
#if not installed numpy
#!pip install numpy

#import
import numpy as np

**Creating Numpy Array**

In [53]:
#Simple 1D array
a = np.array([2,3,4])
b = np.array([1.2, 3.5, 5.1])

print(a,a.dtype,b, b.dtype)

#a = np.array(1,2,3,4)    # WRONG

[2 3 4] int64 [1.2 3.5 5.1] float64


In [54]:
#Specify Data type
c = np.array( [2,3,4] )
print(c,c.dtype)
c = np.array( [2,3,4], dtype="int32" )
#c = np.array( [2,3,4], dtype=np.int16 )
print(c,c.dtype)

[2 3 4] int64
[2 3 4] int32


In [55]:
# Two dimentional Array
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [57]:
#Initialize with all zeros
a = np.zeros((2, 2))
print(a)
#Initialize with ones
a = np.ones((2,2))
print(a)
#Initialize with nothing
a = np.empty((2,2))
print(a)
# Arrange
a = np.arange( 10, 30, 5 )
print(a)
#Identity
a = np.identity(5)
print(a)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[10 15 20 25]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Copy np array**

In [59]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


**Some Basic properties**

In [24]:
a = np.empty((2,2))
#ndarray.ndim
print(a.ndim)
#ndarray.shape
print(a.shape)
#ndarray.size
print(a.size)
#ndarray.dtype
print(a.dtype)
#ndarray.itemsize
print(a.itemsize)
#ndarry.nbytes
print(a.nbytes)

2
(2, 2)
4
float64
8
32


**Shape Manipulation**

In [18]:
a = np.zeros((6,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
a.ravel()  # returns the array, flattened

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# reshape function
a.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#Transpose
a.T

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**Stacking together different arrays**

In [61]:
a = np.random.randint(1,2, size=(3,3))
b = np.random.randint(3,4, size=(3,3))
c = np.vstack((a,b))
print(c)
c = np.hstack((a,b))
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
[[1 1 1 3 3 3]
 [1 1 1 3 3 3]
 [1 1 1 3 3 3]]


**Mathematics**

In [62]:
a = np.array([1,2,3,4])
print(a)
# Adding value to all elements
a + 2

[1 2 3 4]


array([3, 4, 5, 6])

In [33]:
b = np.array([1,0,1,0])
print(a + b)

print(a@b)
print(a*b)

#Todo: Try multiplication for two dimentional array
#np.matmul(a,b)

[2 2 4 4]
4
[1 0 3 0]


**Statistical Functions**

In [63]:
stats = np.ones((2,2))
print(stats)
np.min(stats)
np.max(stats)
np.sum(stats)

[[1. 1.]
 [1. 1.]]


4.0

**Indexing, Slicing and Masking**

In [44]:
#One dimentional
a = np.arange(10)
print(a)
print(a[2])
print(a[2:5])
print(a[2:5:2])
print(a[2:5])
for i in a:
  print(i)
#Todo: create one dimentional array of 20 numbers, in step of 2
#Todo: use loop to print all elements from 5 to 15
#Todo: use loop to print alternate elements from 5 to 15

[0 1 2 3 4 5 6 7 8 9]
2
[2 3 4]
[2 4]
[2 3 4]
0
1
2
3
4
5
6
7
8
9


In [47]:
#Multi Dimentional
a = np.zeros((5,5))
#print(a[start_row: end_row: step,Start_column:End Columns: step])
print(a[2:5,:3])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [64]:
#Masking
a = np.array([1,2,1,1,1,2,2])
print(a>1)
print(a[a>1])



[False  True False False False  True  True]
[2 2 2]
